Update Build_OP_XIAOMI_R3.yml

diff --git a/.github/workflows/Build_OP_XIAOMI_R3.yml b/.github/workflows/Build_OP_XIAOMI_R3.yml
--- a/.github/workflows/Build_OP_XIAOMI_R3.yml
+++ b/.github/workflows/Build_OP_XIAOMI_R3.yml
@@ -70,7 +70,12 @@ jobs:
 
     - name: Configuration Customization
       run: |
-        [[ -d "files" ]] && cp -r files openwrt/files
+        if [[ ! -f "${CONFIG_FILE}" ]]; then
+          echo "❌ Error: Config file ${CONFIG_FILE} not found!"
+          exit 1
+        fi
+        chmod +x ./scripts/customize.sh && ./scripts/customize.sh
+        [[ -d "files" ]] && mv -f files openwrt/files
         cp -fv "${CONFIG_FILE}" openwrt/.config
         cd openwrt && make defconfig
         
